server:
  port: 8888

spring:
  application:
    name: hr-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/charlesluz1994/ms-worker-cloud-configs.git
          username: charlesluz1994
          password: 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