spring:
  application:
    name: hr-eureka-server

server:
  port: 8761
eureka:
  server:
    wait-time-in-ms-when-sync-empty: 0
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka